### ISSUE TITLE
How to adapt the teachable machine to up-to-date Maixpy?

### ISSUE THREAD

**Issue by Createyouraccount-alt** [DeqingSun/Teachable-Machine-on-K210#1]
The most recent Maixpy:
maixpy_v0.5.0_9_g8eba07d_minimum_with_ide_support.bin
is inconsistent with this teachable machine.
linalg module is missing.
How to adapt the teachable machine to up-to-date Maixpy?

**Comment by DeqingSun** [comment]
As I mentioned in Readme. https://github.com/sipeed/MaixPy/pull/232 need to be merged either in your branch or you wait for sipeed to do it.
